name: CI Gradle Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: iosSimulatorArm64Test
            os: macos-latest
          - target: jvmTest
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4.6.0
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Assemble the project
      run: ./gradlew assemble

    - if: ${{ matrix.jvmTest }}
      run: ./gradlew jvmTest
    - if: ${{ matrix.iosSimulatorArm64Test }}
      run: ./gradlew copyiOSTestResources      
           ./gradlew iosSimulatorArm64Test
    
    - name: Run build in a subdirectory
      working-directory: another-build
      run: ./gradlew build
